/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.demo.form;

import com.demo.DAO.ChiNhanhDao;
import com.demo.DAO.CoSoVatChatDao;
import com.demo.model.ChiNhanh;
import com.demo.model.CoSoVatChat;
import com.raven.DAO.PhongDao;
import com.raven.model.PhongChieu;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hohoa
 */
public class Form_CSVC extends javax.swing.JPanel {

    int current;
    int selected;

    CoSoVatChat csvc;
    ChiNhanh cn;
    PhongChieu phong;

    CoSoVatChatDao csvcDAO;
    ChiNhanhDao cnDAO;
    PhongDao phongDAO;

    List<CoSoVatChat> csvc_list;
    List<ChiNhanh> cn_list;
    List<PhongChieu> phong_list;

    DefaultTableModel tblModel = new DefaultTableModel();
    DefaultComboBoxModel cboModel = new DefaultComboBoxModel();

    /**
     * Creates new form Form_CSVC
     */
    public Form_CSVC() {
        initComponents();
        csvcDAO = new CoSoVatChatDao();
        cnDAO = new ChiNhanhDao();
        phongDAO = new PhongDao();

        csvc_list = new ArrayList<>();
        cn_list = new ArrayList<>();
        phong_list = new ArrayList<>();

        fillToCbxChiNhanh();
        fillToCbxPhong();
    }

    public void fillToTable(String maCN) {
        System.out.println(maCN);
        tblModel = (DefaultTableModel) tblCoSoVatChat.getModel();
        csvc_list = csvcDAO.SelectAll(maCN);
        tblModel.setRowCount(0);
        csvc_list.stream().forEach(c -> {
            String trangThai;
            if (c.getTrangthai() == 0) {
                trangThai = "Tốt";
            } else {
                trangThai = "Bảo trì";
            }

            Object[] row = new Object[]{c.getTencn(), c.getTenphong(), c.getTencsvc(), c.getSoluong(), trangThai};
            tblModel.addRow(row);
        });
    }

    public void fillToCbxChiNhanh() {
        cboModel = (DefaultComboBoxModel) cboChiNhanh.getModel();
        cboModel.removeAllElements();
        cn_list = cnDAO.select();

        cn_list.stream().forEach(cn -> {
            cboChiNhanh.addItem(cn.getTenCN());
        });
    }

    public void fillToCbxPhong() {
        cboModel = (DefaultComboBoxModel) cboPhong.getModel();
        cboModel.removeAllElements();
        phong_list = phongDAO.Select();
        HashMap<String, Integer> phong = new HashMap<String, Integer>();
        Set<String> phongKey = phong.keySet();
        for (int i = 0; i < phong_list.size(); i++) {
            phong.put(phong_list.get(i).getTenPhong(), i);
        }
        for (String i : phongKey) {
            cboPhong.addItem(i);
        }
    }

    public void showDetails() {
        CoSoVatChat csvc = csvc_list.get(current);
        cboChiNhanh.setSelectedItem(csvc_list.get(current).getTencn());
        cboPhong.setSelectedItem(csvc_list.get(current).getTenphong());
        txtMaCSVC.setText(csvc.getMacsvc());
        System.out.println(csvc.getMacsvc());
        txtTenCSVC.setText(csvc.getTencsvc());
        txtSoLuong.setText(String.valueOf(csvc.getSoluong()));
        if (csvc.getTrangthai() == 0) {
            rdoTT_Tot.setSelected(true);
        } else {
            rdoTT_BaoTri.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrTrangThai = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cboChiNhanh = new javax.swing.JComboBox<>();
        cboPhong = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaCSVC = new javax.swing.JTextField();
        txtTenCSVC = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        rdoTT_Tot = new javax.swing.JRadioButton();
        rdoTT_BaoTri = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCoSoVatChat = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnCapNhap = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        cboChiNhanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên chi nhánh" }));
        cboChiNhanh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboChiNhanhItemStateChanged(evt);
            }
        });
        cboChiNhanh.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                cboChiNhanhHierarchyChanged(evt);
            }
        });
        cboChiNhanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboChiNhanhMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cboChiNhanhMouseReleased(evt);
            }
        });
        cboChiNhanh.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboChiNhanhPropertyChange(evt);
            }
        });
        cboChiNhanh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cboChiNhanhKeyReleased(evt);
            }
        });
        cboChiNhanh.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cboChiNhanhVetoableChange(evt);
            }
        });

        cboPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên phòng" }));

        jLabel1.setText("Mã CSVC");

        jLabel2.setText("Tên CSVC");

        jLabel3.setText("Số lượng");

        lblTrangThai.setText("Trạng thái");

        btnGrTrangThai.add(rdoTT_Tot);
        rdoTT_Tot.setText("Tốt");

        btnGrTrangThai.add(rdoTT_BaoTri);
        rdoTT_BaoTri.setText("Bảo trì");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(cboPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenCSVC, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtMaCSVC)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTrangThai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTT_Tot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTT_BaoTri)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaCSVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenCSVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrangThai)
                    .addComponent(rdoTT_Tot)
                    .addComponent(rdoTT_BaoTri))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tblCoSoVatChat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Chi nhánh", "Rạp", "Tên CSVC", "Số lượng", "Trạng thái"
            }
        ));
        tblCoSoVatChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCoSoVatChatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCoSoVatChat);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhap.setText("Cập nhật");
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnCapNhap)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhap))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String maphong;

        csvc = new CoSoVatChat();
        phong = new PhongChieu();

        csvc.setMacsvc(txtMaCSVC.getText());
        csvc.setTencsvc(txtTenCSVC.getText());
        phong.setMaPhong(phong_list.get(cboPhong.getSelectedIndex()).getMaPhong());
        csvc.setSoluong(Integer.parseInt(txtSoLuong.getText()));
        if (rdoTT_Tot.isSelected() == true) {
            csvc.setTrangthai(0);
        } else {
            csvc.setTrangthai(1);
        }

        maphong = phong.getMaPhong();

        csvcDAO.Insert(csvc.getMacsvc(), csvc.getTencsvc(), csvc.getMacsvc() + ".png");
        csvcDAO.InsertCTCSVC(csvc.getMacsvc(), maphong, csvc.getSoluong(), csvc.getTrangthai());

        selected = cboChiNhanh.getSelectedIndex() + 1;
        String maCN = "cn" + selected;
        fillToTable(maCN);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        String macn = (String) cboChiNhanh.getSelectedItem();
        try {
            // TODO add your handling code here:

            String maphong;
            String macsvc = txtMaCSVC.getText();
            String tencsvc = txtTenCSVC.getText();
            int soluong = Integer.parseInt(txtSoLuong.getText());
            int trangthai;

            if (rdoTT_Tot.isSelected() == true) {
                trangthai = 0;
            } else {
                trangthai = 1;
            }

            csvc = new CoSoVatChat();
            phong = new PhongChieu();

            phong.setMaPhong(phong_list.get(cboPhong.getSelectedIndex()).getMaPhong());
            csvc.setSoluong(Integer.parseInt(txtSoLuong.getText()));

            maphong = phong.getMaPhong();

            csvcDAO.Update(macsvc, tencsvc, macsvc + ".png");
            csvcDAO.UpdateCTCSVC(macsvc, maphong, soluong, trangthai);

        } catch (SQLException ex) {
            Logger.getLogger(Form_CSVC.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillToTable(macn);
    }//GEN-LAST:event_btnCapNhapActionPerformed

    private void tblCoSoVatChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCoSoVatChatMouseClicked
        // TODO add your handling code here:
        current = tblCoSoVatChat.getSelectedRow();
        showDetails();
    }//GEN-LAST:event_tblCoSoVatChatMouseClicked

    private void cboChiNhanhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboChiNhanhKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChiNhanhKeyReleased

    private void cboChiNhanhHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_cboChiNhanhHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChiNhanhHierarchyChanged

    private void cboChiNhanhPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboChiNhanhPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChiNhanhPropertyChange

    private void cboChiNhanhVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cboChiNhanhVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChiNhanhVetoableChange

    private void cboChiNhanhMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboChiNhanhMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_cboChiNhanhMouseReleased

    private void cboChiNhanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboChiNhanhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChiNhanhMouseClicked

    private void cboChiNhanhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboChiNhanhItemStateChanged
        // TODO add your handling code here:
        selected = cboChiNhanh.getSelectedIndex() + 1;
        String maCN = "cn" + selected;

        fillToTable(maCN);
    }//GEN-LAST:event_cboChiNhanhItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhap;
    private javax.swing.ButtonGroup btnGrTrangThai;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cboChiNhanh;
    private javax.swing.JComboBox<String> cboPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JRadioButton rdoTT_BaoTri;
    private javax.swing.JRadioButton rdoTT_Tot;
    private javax.swing.JTable tblCoSoVatChat;
    private javax.swing.JTextField txtMaCSVC;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenCSVC;
    // End of variables declaration//GEN-END:variables
}
