/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.demo.form;

import java.awt.Font;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ngoc Han
 */
public class Setting extends javax.swing.JPanel {
        int Bold_Plain_Italic_Choose = 1; // biến toàn cục lưu lại kiểu chữ
    String Showdown = "Arial"; // biến toàn cục lưu lại kiểu chữ
    int FontDefault = 1; // lưu lại font chữ mặc định
    String StyleDefault = "Arial"; // lưu lại kiểu chữ mặc định
    int command = 1;

    /**
     * Creates new form Setting
     */
    public Setting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDefault = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblSetting = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtShowdown = new javax.swing.JTextField();
        lblPhongchu = new javax.swing.JLabel();
        btnBold = new javax.swing.JButton();
        btnItalic = new javax.swing.JButton();
        btnPlain = new javax.swing.JButton();
        lblPhongchu1 = new javax.swing.JLabel();
        cbbPhongChu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        btnDefault1 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        btnDefault.setBackground(new java.awt.Color(153, 153, 153));
        btnDefault.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDefault.setForeground(new java.awt.Color(255, 255, 255));
        btnDefault.setText("Mặc định ");
        btnDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefaultActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jEditorPane1);

        jTextField1.setText("jTextField1");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblSetting.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblSetting.setForeground(new java.awt.Color(255, 255, 255));
        lblSetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSetting.setText("Cài đặt ");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÔNG TIN NHÂN VIÊN:  ");

        txtShowdown.setBackground(new java.awt.Color(0, 0, 0));
        txtShowdown.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtShowdown.setForeground(new java.awt.Color(255, 255, 255));
        txtShowdown.setText("Nguyễn Văn A");
        txtShowdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShowdownActionPerformed(evt);
            }
        });

        lblPhongchu.setForeground(new java.awt.Color(255, 255, 255));
        lblPhongchu.setText("KIỂU CHỮ: ");

        btnBold.setBackground(new java.awt.Color(255, 51, 51));
        btnBold.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBold.setForeground(new java.awt.Color(255, 255, 255));
        btnBold.setText("Bold");
        btnBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoldActionPerformed(evt);
            }
        });

        btnItalic.setBackground(new java.awt.Color(204, 204, 204));
        btnItalic.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnItalic.setForeground(new java.awt.Color(255, 255, 255));
        btnItalic.setText("Italic");
        btnItalic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItalicActionPerformed(evt);
            }
        });

        btnPlain.setBackground(new java.awt.Color(204, 204, 204));
        btnPlain.setForeground(new java.awt.Color(255, 255, 255));
        btnPlain.setText("Plain");
        btnPlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlainActionPerformed(evt);
            }
        });

        lblPhongchu1.setForeground(new java.awt.Color(255, 255, 255));
        lblPhongchu1.setText("PHÔNG CHỮ: ");

        cbbPhongChu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Times New Roman", "Tahoma", " " }));
        cbbPhongChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhongChuActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KIỂU IN: ");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Ngang");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Dọc");

        btnDefault1.setBackground(new java.awt.Color(153, 153, 153));
        btnDefault1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDefault1.setForeground(new java.awt.Color(255, 255, 255));
        btnDefault1.setText("Mặc định ");
        btnDefault1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefault1ActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(153, 153, 153));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lblSetting))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1)
                            .addComponent(btnDefault1))
                        .addGap(35, 35, 35)
                        .addComponent(btnSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPhongchu1)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbPhongChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBold)
                                .addGap(128, 128, 128)
                                .addComponent(btnPlain))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtShowdown, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(lblPhongchu))
                                    .addGap(67, 67, 67)
                                    .addComponent(btnItalic))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton2)))
                            .addGap(14, 14, 14))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSetting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtShowdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhongchu)
                    .addComponent(btnBold)
                    .addComponent(btnItalic)
                    .addComponent(btnPlain))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhongchu1)
                    .addComponent(cbbPhongChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDefault1)
                    .addComponent(btnSave))
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtShowdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShowdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShowdownActionPerformed

    private void btnBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoldActionPerformed
        Bold_Plain_Italic_Choose = 1;
        btnItalic.setBackground(Color.WHITE);
        btnItalic.setForeground(Color.darkGray);
        btnItalic.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        btnBold.setBackground(Color.RED);
        btnBold.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnPlain.setBackground(Color.WHITE);
        btnPlain.setForeground(Color.darkGray);
        btnPlain.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        setChange();
    }//GEN-LAST:event_btnBoldActionPerformed

    private void btnItalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItalicActionPerformed
        Bold_Plain_Italic_Choose = 3;
        btnItalic.setBackground(Color.RED);
        btnItalic.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnBold.setBackground(Color.WHITE);
        btnBold.setForeground(Color.DARK_GRAY);
        btnBold.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        btnPlain.setBackground(Color.WHITE);
        btnBold.setForeground(Color.DARK_GRAY);
        btnPlain.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        setChange();
    }//GEN-LAST:event_btnItalicActionPerformed

    private void btnPlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlainActionPerformed
        Bold_Plain_Italic_Choose = 2;
        btnItalic.setBackground(Color.WHITE);
        btnItalic.setForeground(Color.darkGray);
        btnItalic.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        btnBold.setBackground(Color.WHITE);
        btnBold.setForeground(Color.darkGray);
        btnBold.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        btnPlain.setBackground(Color.RED);
        btnPlain.setFont(new Font("Segoe UI", Font.BOLD, 12));
        setChange();
    }//GEN-LAST:event_btnPlainActionPerformed

    private void cbbPhongChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhongChuActionPerformed
        Object object = evt.getSource();
        if (object == cbbPhongChu) {
            Showdown = cbbPhongChu.getSelectedItem().toString();
            setChange();
            return;
        }
    }//GEN-LAST:event_cbbPhongChuActionPerformed

    private void btnDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefaultActionPerformed

        if (FontDefault == 1) {
            btnBoldActionPerformed(evt);
            txtShowdown.setFont(new Font(StyleDefault, Font.BOLD, 12));
        } else if (FontDefault == 2) {
            btnPlainActionPerformed(evt);
            txtShowdown.setFont(new Font(StyleDefault, Font.PLAIN, 12));
        } else if (FontDefault == 3) {
            btnItalicActionPerformed(evt);
            txtShowdown.setFont(new Font(StyleDefault, Font.ITALIC, 12));
        }
        cbbPhongChu.setSelectedItem(StyleDefault);

    }//GEN-LAST:event_btnDefaultActionPerformed

    private void btnDefault1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefault1ActionPerformed

        if (FontDefault == 1) {
            btnBoldActionPerformed(evt);
            txtShowdown.setFont(new Font(StyleDefault, Font.BOLD, 12));
        } else if (FontDefault == 2) {
            btnPlainActionPerformed(evt);
            txtShowdown.setFont(new Font(StyleDefault, Font.PLAIN, 12));
        } else if (FontDefault == 3) {
            btnItalicActionPerformed(evt);
            txtShowdown.setFont(new Font(StyleDefault, Font.ITALIC, 12));
        }
        cbbPhongChu.setSelectedItem(StyleDefault);

    }//GEN-LAST:event_btnDefault1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        FontDefault = Bold_Plain_Italic_Choose;
        System.out.println(FontDefault);
        StyleDefault = Showdown;
        System.out.println(StyleDefault);
        JOptionPane.showMessageDialog(this, "Đã cập nhật lại Font và Style Mặc Định");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBold;
    private javax.swing.JButton btnDefault;
    private javax.swing.JButton btnDefault1;
    private javax.swing.JButton btnItalic;
    private javax.swing.JButton btnPlain;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbPhongChu;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPhongchu;
    private javax.swing.JLabel lblPhongchu1;
    private javax.swing.JLabel lblSetting;
    private javax.swing.JTextField txtShowdown;
    // End of variables declaration//GEN-END:variables

 public void setChange() {
        if (Bold_Plain_Italic_Choose == 1) {
            txtShowdown.setFont(new Font(Showdown, Font.BOLD, 12));
        } else if (Bold_Plain_Italic_Choose == 2) {
            txtShowdown.setFont(new Font(Showdown, Font.PLAIN, 12));
        } else if (Bold_Plain_Italic_Choose == 3) {
            txtShowdown.setFont(new Font(Showdown, Font.ITALIC, 12));
        }
    }

}
