/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.demo.form;

import com.raven.DAO.PhimDao;
import com.raven.DAO.PhongDao;
import com.raven.DAO.XuatChieuDao;
import com.raven.form.Form_ChoNgoi;
import static com.raven.form.Form_ChoNgoi.writeObj;
import com.raven.main.Main;
import com.raven.model.ChiTietGhe;
import com.raven.model.NgayChieu;
import com.raven.model.Phim;
import com.raven.model.ThanhToan;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daokh
 */
public class TablePhim extends javax.swing.JPanel {

    /**
     * Creates new form TablePhim
     */
    PhimDao daophim;
    List<Phim> listPhim;
    List<ChiTietGhe> ListPhong;
    PhongDao daoPhong;
    XuatChieuDao daoXC;
    List<NgayChieu> ngaychieu = new ArrayList<>();
    String maPhong, gioBatDau, maPhim;
    int sttn;
    String url = "http://localhost:8484/Image/poster/";
    public TablePhim() {
        initComponents();
    }
    int stt_xc =0;
    public TablePhim(Phim p,int sttngay, String gio) {
        initComponents();
        daoXC = new XuatChieuDao();
        this.sttn = sttngay;
        this.stt_xc = p.getStt_xc();
        lblTenPhim.setText(p.getTenPhim());
        lblDV.setText(p.getDienVien());
        lblDD.setText(p.getDaoDien());
        lblQG.setText(p.getQuocGia());
        lblTL.setText(p.getThoiLuong());
        lblNSX.setText(String.valueOf(p.getNamSX()));
        lblHinh.setIcon(resizeImage(url + p.getHinh()));
        lblPhong.setText(p.getTenphong());
        maPhong = daoXC.SelectMaPhong(p.getMaPhim(), sttngay);
//        gioBatDau = gioBatDauChieu;
        maPhim = p.getMaPhim();
        gioBatDau = gio;
    }

    public ImageIcon resizeImage(String path) {
        URL temp= null;
        try {
            System.out.println(path);
            temp = new URL(path);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TablePhim.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon ii = new ImageIcon(temp);
        
        ImageIcon imageIcon = new ImageIcon(ii.getImage().getScaledInstance(150, 300, java.awt.Image.SCALE_SMOOTH));
        return imageIcon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHinh = new javax.swing.JLabel();
        lblTenPhim = new javax.swing.JLabel();
        lblDienVien = new javax.swing.JLabel();
        lblDaoDien = new javax.swing.JLabel();
        lblQuocGia = new javax.swing.JLabel();
        lblThoiLuong = new javax.swing.JLabel();
        lblNamSX = new javax.swing.JLabel();
        lblDV = new javax.swing.JLabel();
        lblDD = new javax.swing.JLabel();
        lblQG = new javax.swing.JLabel();
        lblTL = new javax.swing.JLabel();
        lblNSX = new javax.swing.JLabel();
        lblNamSX1 = new javax.swing.JLabel();
        lblPhong = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblHinh.setForeground(new java.awt.Color(255, 255, 255));

        lblTenPhim.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTenPhim.setForeground(new java.awt.Color(255, 0, 51));

        lblDienVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDienVien.setForeground(new java.awt.Color(255, 255, 255));
        lblDienVien.setText("Diễn viên :");

        lblDaoDien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDaoDien.setForeground(new java.awt.Color(255, 255, 255));
        lblDaoDien.setText("Đạo diễn :");

        lblQuocGia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblQuocGia.setForeground(new java.awt.Color(255, 255, 255));
        lblQuocGia.setText("Quốc gia :");

        lblThoiLuong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblThoiLuong.setForeground(new java.awt.Color(255, 255, 255));
        lblThoiLuong.setText("Thời lượng :");

        lblNamSX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNamSX.setForeground(new java.awt.Color(255, 255, 255));
        lblNamSX.setText("Năm SX :");

        lblDV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDV.setForeground(new java.awt.Color(255, 255, 255));

        lblDD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDD.setForeground(new java.awt.Color(255, 255, 255));

        lblQG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblQG.setForeground(new java.awt.Color(255, 255, 255));

        lblTL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTL.setForeground(new java.awt.Color(255, 255, 255));

        lblNSX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNSX.setForeground(new java.awt.Color(255, 255, 255));

        lblNamSX1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNamSX1.setForeground(new java.awt.Color(255, 255, 255));
        lblNamSX1.setText("Phòng:");

        lblPhong.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuocGia)
                        .addGap(18, 18, 18)
                        .addComponent(lblQG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDaoDien)
                        .addGap(18, 18, 18)
                        .addComponent(lblDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDienVien)
                        .addGap(18, 18, 18)
                        .addComponent(lblDV, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTenPhim)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThoiLuong)
                            .addComponent(lblNamSX)
                            .addComponent(lblNamSX1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTL, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNSX, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(lblPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTenPhim)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDienVien)
                            .addComponent(lblDV))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDaoDien)
                            .addComponent(lblDD))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuocGia)
                            .addComponent(lblQG))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblThoiLuong)
                            .addComponent(lblTL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamSX)
                            .addComponent(lblNSX))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamSX1)
                            .addComponent(lblPhong))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        try {
            ThanhToan tt = (ThanhToan) Form_ChoNgoi.readObj("temp.txt");
            tt.setMaPhong(maPhong);
            tt.setMaPhim(maPhim);
            tt.setSTT(sttn);
            tt.setStt_xc(stt_xc);
            System.out.println(sttn);
            writeObj("temp.txt", tt);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(TablePhim.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TablePhim.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TablePhim.class.getName()).log(Level.SEVERE, null, ex);
        }
        Main.mainF.removeAll();
        Main.mainF.add(new Form_ChoNgoi(maPhim,gioBatDau));
        Main.mainF.repaint();
        Main.mainF.revalidate();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDD;
    private javax.swing.JLabel lblDV;
    private javax.swing.JLabel lblDaoDien;
    private javax.swing.JLabel lblDienVien;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblNSX;
    private javax.swing.JLabel lblNamSX;
    private javax.swing.JLabel lblNamSX1;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblQG;
    private javax.swing.JLabel lblQuocGia;
    private javax.swing.JLabel lblTL;
    private javax.swing.JLabel lblTenPhim;
    private javax.swing.JLabel lblThoiLuong;
    // End of variables declaration//GEN-END:variables
}
