/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.model;

import javax.swing.ImageIcon;

/**
 *
 * @author Daokh
 */
public class Model_ChonTopping extends javax.swing.JPanel {

    /**
     * Creates new form Model_ChonTopping
     */
    public Model_ChonTopping() {
        initComponents();
        
    }
    Topping tp;

    public Model_ChonTopping(Topping tp) {
        initComponents();
        this.tp = tp;
        chkTenTopping.setText(tp.getTenTopping());
        lblHinh.setIcon(resizeImage("src/main/resources/topping/"+tp.getHinh()));
    }
   public ImageIcon resizeImage(String path) {
        ImageIcon ii = new ImageIcon(path);
        ImageIcon imageIcon = new ImageIcon(ii.getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH));
        return imageIcon;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        chkTenTopping = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        snSoLuong = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel1.add(lblHinh);

        chkTenTopping.setText("jCheckBox1");
        chkTenTopping.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkTenToppingItemStateChanged(evt);
            }
        });
        jPanel1.add(chkTenTopping);

        jLabel1.setText("Số lượng");
        jPanel1.add(jLabel1);
        jPanel1.add(snSoLuong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkTenToppingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkTenToppingItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chkTenToppingItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkTenTopping;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JSpinner snSoLuong;
    // End of variables declaration//GEN-END:variables
}
