/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.DAO.PhimDao;
import com.raven.model.NgayChieu;
import com.raven.model.Phim;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import java.text.*;
import java.util.Date;

/**
 *
 * @author QingShan
 */
public class Form_QuanLyLichChieu extends javax.swing.JPanel {

    List<Phim> ListPhim = new ArrayList<>();
    List<NgayChieu> ListGioTheoNgayPhim = new ArrayList<>();
    PhimDao daophim;
    String ngayChieuPhim;
    int index;

    /**
     * Creates new form Form_QuanLyLichChieu
     */
    public Form_QuanLyLichChieu() {
        initComponents();
        daophim = new PhimDao();
        
    }

    

    public void FillPhim() {
        ListPhim = daophim.Select();
        cboPhim.removeAllItems();
        ListPhim.stream().forEach(s -> {
            cboPhim.addItem(s.getTenPhim());
        });
    }

    public void FillGio() {
        String maPhim = ListPhim.get(index).getMaPhim();
        ListGioTheoNgayPhim = daophim.GioCuaPhim(maPhim, ngayChieuPhim);
        ListGioTheoNgayPhim.stream().forEach(s -> {

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        cboPhim = new javax.swing.JComboBox<>();
        ChonNgay = new com.toedter.calendar.JDateChooser();
        times = new javax.swing.JPanel();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        jSpinner1 = new javax.swing.JSpinner(sm);

        jLabel1.setText("Ngày Chiếu");

        jLabel2.setText("Phim");

        btnThem.setText("Thêm");

        btnCapNhat.setText("Cập Nhật");

        btnXoa.setText("Xóa");

        cboPhim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPhimItemStateChanged(evt);
            }
        });

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner1, "HH:mm");
        jSpinner1.setEditor(de);

        javax.swing.GroupLayout timesLayout = new javax.swing.GroupLayout(times);
        times.setLayout(timesLayout);
        timesLayout.setHorizontalGroup(
            timesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timesLayout.createSequentialGroup()
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        timesLayout.setVerticalGroup(
            timesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(50, 50, 50)
                                .addComponent(btnCapNhat)
                                .addGap(55, 55, 55)
                                .addComponent(btnXoa))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(ChonNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(332, 332, 332))
                                    .addComponent(cboPhim, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(times, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboPhim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChonNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(times, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboPhimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPhimItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (cboPhim.getSelectedIndex() >= 0) {
                index = cboPhim.getSelectedIndex();
                FillGio();
            }
        }
    }//GEN-LAST:event_cboPhimItemStateChanged

    private void ChonNgayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ChonNgayPropertyChange
        // TODO add your handling code here:
        if (ChonNgay.getDate() != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
            SimpleDateFormat timeFormat = new SimpleDateFormat("hh: mm");
            Date date = ChonNgay.getDate();
            Date time = ChonNgay.getDate();
            ngayChieuPhim = dateFormat.format(date);
            String GioChieuPhim = timeFormat.format(time);
            FillPhim();
            System.out.println(GioChieuPhim);
        }
    }//GEN-LAST:event_ChonNgayPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ChonNgay;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboPhim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel times;
    // End of variables declaration//GEN-END:variables
}
